'use client';

import { useState } from 'react';

type Operation = 'format' | 'minify' | null;

const sampleHtml = `<div class="container"><h1>Hello World</h1><p>This is a paragraph with <a href="#">a link</a> inside.</p><ul><li>Item 1</li><li>Item 2</li></ul><pre>line 1
  line 2
    line 3</pre><img src="avatar.png" alt="Avatar"><script>const message = "a   b"; console.log(message);</script></div>`;

export default function HtmlFormatter() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [indentSize, setIndentSize] =
    useState<2 | 4>(2);
  const [isProcessing, setIsProcessing] =
    useState(false);
  const [operation, setOperation] =
    useState<Operation>(null);

  const resetResult = () => {
    setOutput('');
    setError('');
    setCopied(false);
    setOperation(null);
  };

  const formatHtml = async () => {
    if (!input.trim()) return;

    setIsProcessing(true);
    setError('');
    setOutput('');
    setCopied(false);

    try {
      const beautifyModule = await import(
        'js-beautify'
      );

      const beautify =
        beautifyModule.default;

      const formatted = beautify.html(
        input,
        {
          indent_size: indentSize,
          indent_char: ' ',
          preserve_newlines: true,
          max_preserve_newlines: 2,
          wrap_line_length: 0,
          indent_scripts: 'normal',
          end_with_newline: false,

          // Preserve whitespace-sensitive and embedded content.
          content_unformatted: [
            'pre',
            'textarea',
            'script',
            'style',
          ],
        }
      );

      setOutput(formatted.trim());
      setOperation('format');
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : 'Unable to format this HTML.'
      );
      setOperation(null);
    } finally {
      setIsProcessing(false);
    }
  };

  const minifyHtml = async () => {
    if (!input.trim()) return;

    setIsProcessing(true);
    setError('');
    setOutput('');
    setCopied(false);

    try {
      const { minify } = await import(
        'html-minifier-terser/dist/htmlminifier.esm.bundle'
      );

      const minified = await minify(
        input,
        {
          html5: true,

          collapseWhitespace: true,
          conservativeCollapse: true,

          // Preserve potentially meaningful comments.
          removeComments: false,

          // Do not perform structural rewrites.
          removeAttributeQuotes: false,
          removeEmptyAttributes: false,
          removeEmptyElements: false,
          removeOptionalTags: false,
          removeRedundantAttributes: false,

          // Keep embedded languages unchanged.
          minifyCSS: false,
          minifyJS: false,
          minifyURLs: false,

          // Avoid unrelated rewrites.
          decodeEntities: false,
          sortAttributes: false,
          sortClassName: false,
          useShortDoctype: false,

          // Avoid silently accepting malformed markup.
          continueOnParseError: false,

          // Do not inject parser-generated wrapper tags.
          includeAutoGeneratedTags: false,

          // Preserve XHTML-style closing slashes if present.
          keepClosingSlash: true,
        }
      );

      setOutput(minified.trim());
      setOperation('minify');
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : 'Unable to minify this HTML.'
      );
      setOperation(null);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleCopy = async () => {
    if (!output) return;

    try {
      await navigator.clipboard.writeText(
        output
      );

      setCopied(true);

      window.setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch {
      setCopied(false);
    }
  };

  const handleClear = () => {
    setInput('');
    resetResult();
  };

  const handleLoadSample = () => {
    setInput(sampleHtml);
    resetResult();
  };

  const inputBytes = new Blob([
    input,
  ]).size;

  const outputBytes = new Blob([
    output,
  ]).size;

  const savedBytes =
    operation === 'minify'
      ? Math.max(
          0,
          inputBytes - outputBytes
        )
      : 0;

  const savedPercent =
    operation === 'minify' &&
    inputBytes > 0
      ? Math.max(
          0,
          Math.round(
            ((inputBytes - outputBytes) /
              inputBytes) *
              100
          )
        )
      : 0;

  return (
    <div className="space-y-6 text-text-primary">
      <div className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <label
            htmlFor="html-input"
            className="text-sm font-medium text-text-primary"
          >
            Input HTML
          </label>

          <div className="flex items-center gap-2 text-xs">
            <button
              type="button"
              onClick={handleLoadSample}
              className="font-medium text-brand-cyan transition-colors hover:text-text-primary"
            >
              Load Sample
            </button>

            <span
              aria-hidden="true"
              className="text-text-muted"
            >
              /
            </span>

            <button
              type="button"
              onClick={handleClear}
              className="font-medium text-text-muted transition-colors hover:text-text-primary"
            >
              Clear
            </button>
          </div>
        </div>

        <textarea
          id="html-input"
          value={input}
          onChange={(event) => {
            setInput(event.target.value);
            resetResult();
          }}
          placeholder="<div><h1>Title</h1><p>Paragraph text</p></div>"
          spellCheck={false}
          className="h-52 w-full resize-y rounded-xl border border-border bg-surface-900 p-4 font-mono text-sm leading-6 text-text-primary outline-none transition focus:border-brand-cyan focus:ring-2 focus:ring-brand-cyan/20"
        />

        <div className="text-xs text-text-muted">
          {inputBytes.toLocaleString()}{' '}
          bytes input
        </div>
      </div>

      <div className="flex flex-wrap items-end justify-between gap-4">
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={formatHtml}
            disabled={
              !input.trim() ||
              isProcessing
            }
            className="rounded-lg bg-brand-blue px-4 py-2 text-sm font-medium text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
          >
            {isProcessing &&
            operation !== 'minify'
              ? 'Formatting…'
              : 'Format HTML'}
          </button>

          <button
            type="button"
            onClick={minifyHtml}
            disabled={
              !input.trim() ||
              isProcessing
            }
            className="rounded-lg border border-border bg-surface-800 px-4 py-2 text-sm font-medium text-text-primary transition hover:border-brand-cyan/50 disabled:cursor-not-allowed disabled:opacity-40"
          >
            {isProcessing &&
            operation !== 'format'
              ? 'Minifying…'
              : 'Minify HTML'}
          </button>
        </div>

        <div className="space-y-1">
          <label
            htmlFor="html-indent-size"
            className="block text-xs text-text-muted"
          >
            Format indentation
          </label>

          <select
            id="html-indent-size"
            value={indentSize}
            onChange={(event) =>
              setIndentSize(
                Number(
                  event.target.value
                ) as 2 | 4
              )
            }
            className="rounded-lg border border-border bg-surface-900 px-3 py-2 text-sm text-text-primary outline-none transition focus:border-brand-cyan focus:ring-2 focus:ring-brand-cyan/20"
          >
            <option value={2}>
              2 spaces
            </option>

            <option value={4}>
              4 spaces
            </option>
          </select>
        </div>
      </div>

      <div className="rounded-xl border border-brand-cyan/20 bg-brand-cyan/5 p-4">
        <p className="text-xs leading-5 text-text-secondary">
          Formatting preserves content
          inside pre, textarea, script,
          and style elements. Minification
          uses conservative whitespace
          collapsing and does not minify
          embedded JavaScript or CSS.
        </p>
      </div>

      {error && (
        <div
          role="alert"
          className="rounded-xl border border-danger/30 bg-danger/10 p-4"
        >
          <p className="font-mono text-xs uppercase tracking-wide text-danger">
            HTML error
          </p>

          <p className="mt-2 break-words text-sm leading-6 text-text-secondary">
            {error}
          </p>
        </div>
      )}

      {output && (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <p className="text-sm font-medium text-text-primary">
                {operation === 'format'
                  ? 'Formatted HTML'
                  : 'Minified HTML'}
              </p>

              <p className="mt-1 text-xs text-text-muted">
                {outputBytes.toLocaleString()}{' '}
                bytes output
              </p>
            </div>

            <button
              type="button"
              onClick={handleCopy}
              className="rounded-lg border border-success/30 bg-success/10 px-3 py-1.5 text-xs font-medium text-success transition hover:bg-success/15"
            >
              {copied
                ? 'Copied!'
                : 'Copy Result'}
            </button>
          </div>

          {operation === 'minify' && (
            <div className="grid gap-3 rounded-xl border border-brand-blue/20 bg-brand-blue/5 p-4 sm:grid-cols-3">
              <div>
                <span className="block text-xs text-text-muted">
                  Input
                </span>

                <strong className="mt-1 block font-mono text-sm">
                  {inputBytes.toLocaleString()}{' '}
                  bytes
                </strong>
              </div>

              <div>
                <span className="block text-xs text-text-muted">
                  Output
                </span>

                <strong className="mt-1 block font-mono text-sm">
                  {outputBytes.toLocaleString()}{' '}
                  bytes
                </strong>
              </div>

              <div>
                <span className="block text-xs text-text-muted">
                  Saved
                </span>

                <strong className="mt-1 block font-mono text-sm">
                  {savedBytes.toLocaleString()}{' '}
                  bytes ({savedPercent}%)
                </strong>
              </div>
            </div>
          )}

          <pre className="max-h-[32rem] w-full overflow-auto whitespace-pre-wrap break-words rounded-xl border border-border bg-surface-900 p-4 font-mono text-sm leading-6 text-success">
            {output}
          </pre>
        </div>
      )}
    </div>
  );
}
